<?php
/**
 * Created by PhpStorm.
 * User: LENOVO
 * Date: 2019/10/26
 * Time: 17:31
 */

namespace app\admin\controller;


use think\Controller;

class Shuju extends Controller
{
public function _initialize()
{
    parent::_initialize(); // TODO: Change the autogenerated stub
}
public function shuju(){
    return view('index');
}
}