<?php

namespace app\index\controller;

use think\Controller;
use think\Db;

class Index extends  Base
{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->assign('nid',0);
        $this->assign('title','首页');
        $news = Db::table('news')->order('wid','asc')->select();
        $this->assign('news',$news);
        return view();
    }
    public function news(){
        $this->assign('nid',6);
        $this->assign('title','新闻');
        $wid = $this->request->get('wid');
        $news1 = Db::table('news')->where('wid',$wid)->find();
        $this->assign('news',$news1);
        $jumpt = Db::table('news')->where('wid','<',$wid)->order('wid','desc')->limit(0,1)->find();
        $this->assign('jumpt',$jumpt);
        $jumpb = Db::table('news')->where('wid','>',$wid)->order('wid','asc')->limit(0,1)->find();
        $this->assign('jumpb',$jumpb);
        return $this->fetch();
    }

}
